%%
clc;
clear;
close all;

%%
niiData_hdr = struct('hk',struct(   'sizeof_hdr',348,...
                                    'data_type','',...
                                    'db_name','',...
                                    'extents',0,...
                                    'session_error',0,...
                                    'regular','r',...
                                    'dim_info',0),...
                     'dime',struct( 'dim',[0,0,0,0,0,0,0,0],...
                                    'intent_p1',0,...
                                    'intent_p2',0,...
                                    'intent_p3',0,...
                                    'intent_code',0,...
                                    'datatype',0,...
                                    'bitpix',0,...
                                    'slice_start',0,...
                                    'pixdim',[0,0,0,0,0,0,0,0],...
                                    'vox_offset',0,...
                                    'scl_slope',0,...
                                    'scl_inter',0,...
                                    'slice_end',0,...
                                    'slice_code',0,...
                                    'xyzt_units',0,...
                                    'cal_max',0,...
                                    'cal_min',0,...
                                    'slice_duration',0,...
                                    'toffset',0,...
                                    'glmax',0,...
                                    'glmin',0),...
                    'hist',struct(  'descrip','',...
                                    'aux_file','',...
                                    'qform_code',0,...
                                    'sform_code',0,...
                                    'quatern_b',0,...
                                    'quatern_c',0,...
                                    'quatern_d',0,...
                                    'qoffset_x',0,...
                                    'qoffset_y',0,...
                                    'qoffset_z',0,...
                                    'srow_x',[0,0,0,0],...
                                    'srow_y',[0,0,0,0],...
                                    'srow_z',[0,0,0,0],...
                                    'intent_name','',...
                                    'magic','',...
                                    'originator',[0,0,0,0,0]));

%%
addpath(genpath(pwd));
data_hdr = load_nii_hdr('D:\Space\moyamoya-1\moyamoya_gui\Moyamoya Processing\experiment data\pu_mra_tof.nii');
data_hdr_1 = load_nii_hdr('D:\1.nii');
data_hdr_2 = load_nii_hdr('D:\Space\moyamoya-1\moyamoya_gui\Moyamoya Processing\experiment data\pu_swi_m.nii');